# Generated by Django 5.2.10 on 2026-01-21 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['form_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('screening_number', models.CharField(blank=True, max_length=50)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('critical', 'Critical')], default='minor_issues', max_length=20)),
                ('is_clean', models.BooleanField(default=False)),
                ('issues_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=20)),
                ('site_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('investigator_name', models.CharField(max_length=200)),
                ('coordinator_name', models.CharField(blank=True, max_length=200)),
                ('coordinator_email', models.EmailField(blank=True, max_length=254)),
                ('dqi_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['site_number'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=50, unique=True)),
                ('study_name', models.CharField(max_length=200)),
                ('protocol_number', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('I', 'Phase I'), ('II', 'Phase II'), ('III', 'Phase III'), ('IV', 'Phase IV')], default='III', max_length=20)),
                ('therapeutic_area', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('meddra', 'MedDRA Coding'), ('whodd', 'WHO-DD Coding'), ('other', 'Other Coding')], max_length=50)),
                ('term', models.CharField(max_length=200)),
                ('suggested_code', models.CharField(blank=True, max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_issues', to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=50, unique=True)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(choices=[('missing_data', 'Missing Data'), ('inconsistency', 'Data Inconsistency'), ('clarification', 'Clarification Needed'), ('protocol_deviation', 'Protocol Deviation')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('opened_date', models.DateField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('days_open', models.IntegerField(default=0)),
                ('response_text', models.TextField(blank=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='base.form')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='base.patient')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-opened_date'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='base.site'),
        ),
        migrations.CreateModel(
            name='DQIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dqi_score', models.FloatField()),
                ('missing_data_score', models.FloatField(default=0)),
                ('query_score', models.FloatField(default=0)),
                ('visit_completion_score', models.FloatField(default=0)),
                ('verification_score', models.FloatField(default=0)),
                ('coding_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dqi_history', to='base.site')),
            ],
            options={
                'verbose_name_plural': 'DQI Histories',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('dqi_drop', 'DQI Score Drop'), ('query_age', 'Old Queries'), ('missing_visits', 'Missing Visits Pattern'), ('site_capacity', 'Site Capacity Issue'), ('database_lock', 'Database Lock Risk')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified_users', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='base.patient')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='base.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='base.study'),
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('missing_labs', 'Missing Lab Data'), ('missing_visits', 'Missing Visits/Pages'), ('coding_issues', 'Coding Issues'), ('inactivated_forms', 'Inactivated Forms'), ('visit_projections', 'Visit Projections'), ('open_queries', 'Open Queries')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='base.study')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('summary', 'Executive Summary'), ('root_cause', 'Root Cause Analysis'), ('prediction', 'Predictive Analysis'), ('recommendation', 'Recommendation'), ('comparative', 'Comparative Analysis')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='base.patient')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='base.site')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='base.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=20)),
                ('visit_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_missing', models.BooleanField(default=False)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.patient')),
            ],
            options={
                'ordering': ['visit_number'],
                'unique_together': {('patient', 'visit_number')},
            },
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=200)),
                ('test_code', models.CharField(blank=True, max_length=50)),
                ('result_value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('is_missing', models.BooleanField(default=False)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_data', to='base.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_data', to='base.visit')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='base.visit'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('site', 'patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('study', 'site_number')},
        ),
    ]
