# Generated by Django 5.2.10 on 2026-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_id',
            field=models.CharField(max_length=50),
        ),
    ]
