# Generated by Django 5.2.10 on 2026-01-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_query_query_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
